"""criar tabela manutencao_veiculos

Revision ID: 0810561c0210
Revises: 64d71d47c61b
Create Date: 2026-04-22 14:54:04.189315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0810561c0210'
down_revision: Union[str, Sequence[str], None] = '64d71d47c61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manutencoes_veiculo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_manutencao', sa.Enum('preventiva', 'corretiva', name='tipomanutencao'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('agendada', 'emAndamento', 'concluida', 'cancelada', name='statusmanutencao'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manutencoes_veiculo')
    # ### end Alembic commands ###
