"""create users table

Revision ID: 52f054aa4b5f
Revises: 24aef335d923
Create Date: 2026-05-18 21:06:02.330846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f054aa4b5f'
down_revision: Union[str, Sequence[str], None] = '24aef335d923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postos_combustivel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('preco_combustivel', sa.Float(), nullable=True),
    sa.Column('gasoleo', sa.Float(), nullable=True),
    sa.Column('gasolina', sa.Float(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'gerente', name='papelusuario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lembretes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.Enum('manutencao', 'documentacao', 'revisao', 'outro', name='tipo_despesa'), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', name='tipo_despesa'), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('motorista_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lembretes')
    op.drop_table('usuarios')
    op.drop_table('postos_combustivel')
    # ### end Alembic commands ###
