"""configuracoes_medidas

Revision ID: 6246cc321bde
Revises: d87fbfd21b58
Create Date: 2026-04-22 15:58:46.394145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6246cc321bde'
down_revision: Union[str, Sequence[str], None] = 'd87fbfd21b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_medidas',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('unidade_distancia', sa.Enum('km', 'mi', name='unidadedistancia'), nullable=True),
    sa.Column('unidade_consumo_combustivel', sa.Enum('kmL', 'kmgal', name='unidadeconsumo'), nullable=True),
    sa.Column('unidade_peso', sa.Enum('kg', 'lb', name='unidadepeso'), nullable=True),
    sa.Column('unidade_temperatura', sa.Enum('celsius', 'fahrenheit', name='unidadetemperatura'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes_medidas')
    # ### end Alembic commands ###
