"""viagem model

Revision ID: 63694978501c
Revises: 5f28315234f3
Create Date: 2026-05-23 17:54:57.107071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63694978501c'
down_revision: Union[str, Sequence[str], None] = '5f28315234f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viagens', 'status',
               existing_type=mysql.ENUM('agendada', 'em_andamento', 'concluida', 'cancelada'),
               type_=sa.Enum('planejada', 'em_andamento', 'concluida', 'cancelada', name='statusviagem'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viagens', 'status',
               existing_type=sa.Enum('planejada', 'em_andamento', 'concluida', 'cancelada', name='statusviagem'),
               type_=mysql.ENUM('agendada', 'em_andamento', 'concluida', 'cancelada'),
               existing_nullable=False)
    # ### end Alembic commands ###
