"""criar tabela despesas

Revision ID: 64d71d47c61b
Revises: 7a1fa11cc11a
Create Date: 2026-04-21 21:06:29.757097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d71d47c61b'
down_revision: Union[str, Sequence[str], None] = '7a1fa11cc11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('recibo', sa.String(length=255), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    # ### end Alembic commands ###
