"""criar tabela postos combustivel

Revision ID: 6758a76a61d0
Revises: b65bb92cbbe3
Create Date: 2026-04-21 19:38:07.796672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6758a76a61d0'
down_revision: Union[str, Sequence[str], None] = 'b65bb92cbbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postos_combustivel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('preco_combustivel', sa.Float(), nullable=True),
    sa.Column('gasoleo', sa.Float(), nullable=True),
    sa.Column('gasolina', sa.Float(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postos_combustivel')
    # ### end Alembic commands ###
