"""adicionar relacionamento a viagens

Revision ID: 694176f4118b
Revises: ada76db0e669
Create Date: 2026-04-21 18:20:28.023169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '694176f4118b'
down_revision: Union[str, Sequence[str], None] = 'ada76db0e669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viagens', 'motorista_id')
    op.drop_column('viagens', 'veiculo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagens', sa.Column('veiculo_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('viagens', sa.Column('motorista_id', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
