"""atualizar os ENUM do manutencao_veiculos

Revision ID: 7585044e82ea
Revises: dcd6f5089889
Create Date: 2026-04-27 18:14:24.829807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7585044e82ea'
down_revision: Union[str, Sequence[str], None] = 'dcd6f5089889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
