"""criar tabela lembretes

Revision ID: 8b032554eb4b
Revises: 6758a76a61d0
Create Date: 2026-04-21 19:58:51.603984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b032554eb4b'
down_revision: Union[str, Sequence[str], None] = '6758a76a61d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lembretes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('motorista_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lembretes')
    # ### end Alembic commands ###
