"""lembretes

Revision ID: 9203d3c30f19
Revises: bf8c701f1d59
Create Date: 2026-05-23 22:29:36.323709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9203d3c30f19'
down_revision: Union[str, Sequence[str], None] = 'bf8c701f1d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lembretes_ibfk_2'), 'lembretes', type_='foreignkey')
    op.drop_column('lembretes', 'motorista_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lembretes', sa.Column('motorista_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('lembretes_ibfk_2'), 'lembretes', 'motoristas', ['motorista_id'], ['id'])
    # ### end Alembic commands ###
