"""relacoes

Revision ID: 9a77e980249a
Revises: 
Create Date: 2026-05-18 15:22:55.983196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a77e980249a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('postos_combustivel')
    op.drop_table('lembretes')
    op.alter_column('configuracoes_medidas', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('despesas', 'tipo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('combustivel', 'manutencao', 'seguro', 'pneu', 'lavagem', 'outro', name='tipo_despesa'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('despesas', 'tipo',
               existing_type=sa.Enum('combustivel', 'manutencao', 'seguro', 'pneu', 'lavagem', 'outro', name='tipo_despesa'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('configuracoes_medidas', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_table('lembretes',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_agendada', mysql.DATETIME(), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=True),
    sa.Column('completado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('prioridade', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('veiculo_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('motorista_id', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], name=op.f('lembretes_ibfk_1')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('lembretes_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('postos_combustivel',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('provincia', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('preco_combustivel', mysql.FLOAT(), nullable=True),
    sa.Column('gasoleo', mysql.FLOAT(), nullable=True),
    sa.Column('gasolina', mysql.FLOAT(), nullable=True),
    sa.Column('data_cadastro', sa.DATE(), nullable=True),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('papel', mysql.ENUM('admin', 'gerente'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###
