"""adicionar relacionamento a viagens

Revision ID: ada76db0e669
Revises: 18c0a43cfd6a
Create Date: 2026-04-21 18:11:26.920187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada76db0e669'
down_revision: Union[str, Sequence[str], None] = '18c0a43cfd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viagens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorista_id', sa.String(length=50), nullable=False),
    sa.Column('veiculo_id', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('local_partida', sa.String(length=255), nullable=True),
    sa.Column('local_destino', sa.String(length=255), nullable=True),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('combustivel_gasto', sa.Float(), nullable=True),
    sa.Column('custo_viagem', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagens')
    # ### end Alembic commands ###
