"""initial

Revision ID: ae06ac5ca275
Revises: 
Create Date: 2026-05-22 17:47:04.727966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae06ac5ca275'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_empresa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome_empresa', sa.String(length=150), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes_medidas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unidade_distancia', sa.Enum('km', 'mi', name='unidadedistancia'), nullable=True),
    sa.Column('unidade_consumo_combustivel', sa.Enum('kmL', 'kmgal', name='unidadeconsumo'), nullable=True),
    sa.Column('unidade_peso', sa.Enum('kg', 'lb', name='unidadepeso'), nullable=True),
    sa.Column('unidade_temperatura', sa.Enum('celsius', 'fahrenheit', name='unidadetemperatura'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('postos_combustivel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('preco_gasoleo', sa.Float(), nullable=True),
    sa.Column('preco_gasolina', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('manutencao', 'reparo', 'inspecao', name='tiposervico'), nullable=False),
    sa.Column('custo_estimado', sa.Float(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('numero_carta', sa.String(length=50), nullable=False),
    sa.Column('numero_bi', sa.String(length=50), nullable=False),
    sa.Column('categoria_carta', sa.String(length=10), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_validade_carta', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motoristas_id'), 'motoristas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'gerente', name='papelusuario'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('placa', sa.String(length=15), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('carro', 'caminhao', 'caminhonete', 'motorizada', 'autocarro', 'mini_autocarro', name='tipoveiculo'), nullable=True),
    sa.Column('capacidade_carga', sa.Float(), nullable=True),
    sa.Column('combustivel', sa.Enum('gasolina', 'etanol', 'diesel', 'eletrico', name='combustivel'), nullable=True),
    sa.Column('consumo_medio', sa.Float(), nullable=True),
    sa.Column('ultima_revisao', sa.DateTime(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'placa', name='uq_veiculo_empresa_placa'),
    sa.UniqueConstraint('empresa_id', 'vin', name='uq_veiculo_empresa_vin')
    )
    op.create_table('despesas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('combustivel', 'manutencao', 'seguro', 'pneu', 'lavagem', 'outro', name='tipo_despesa'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('recibo', sa.String(length=255), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lembretes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.Enum('manutencao', 'documentacao', 'revisao', 'outro', name='tipo_lembrete'), nullable=False),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', name='prioridade_lembrete'), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('motorista_id', sa.String(length=36), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencoes_veiculo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_manutencao', sa.Enum('preventiva', 'corretiva', 'manutencao', 'reparo', 'inspecao', name='tipomanutencao'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('agendada', 'emAndamento', 'concluida', 'cancelada', name='statusmanutencao'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('local_partida', sa.String(length=255), nullable=False),
    sa.Column('local_destino', sa.String(length=255), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('quilometragem_inicial', sa.Float(), nullable=True),
    sa.Column('quilometragem_final', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('agendada', 'em_andamento', 'concluida', 'cancelada', name='statusviagem'), nullable=False),
    sa.Column('combustivel_gasto', sa.Float(), nullable=True),
    sa.Column('custo_viagem', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('motorista_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viagens_id'), 'viagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viagens_id'), table_name='viagens')
    op.drop_table('viagens')
    op.drop_table('manutencoes_veiculo')
    op.drop_table('lembretes')
    op.drop_table('despesas')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_motoristas_id'), table_name='motoristas')
    op.drop_table('motoristas')
    op.drop_table('servicos')
    op.drop_table('postos_combustivel')
    op.drop_table('empresas')
    op.drop_table('configuracoes_medidas')
    op.drop_table('configuracoes_empresa')
    # ### end Alembic commands ###
