"""update pc

Revision ID: b4df4a7d9cee
Revises: ae06ac5ca275
Create Date: 2026-05-22 18:36:43.095542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4df4a7d9cee'
down_revision: Union[str, Sequence[str], None] = 'ae06ac5ca275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postos_combustivel', sa.Column('empresa_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'postos_combustivel', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'postos_combustivel', type_='foreignkey')
    op.drop_column('postos_combustivel', 'empresa_id')
    # ### end Alembic commands ###
