"""relacao motorista viagem

Revision ID: b65bb92cbbe3
Revises: 345e9f55d842
Create Date: 2026-04-21 18:49:09.022105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65bb92cbbe3'
down_revision: Union[str, Sequence[str], None] = '345e9f55d842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_motoristas_id'), 'motoristas', ['id'], unique=False)
    op.add_column('viagens', sa.Column('motorista_id', sa.String(length=36), nullable=True))
    op.add_column('viagens', sa.Column('veiculo_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_viagens_id'), 'viagens', ['id'], unique=False)
    op.create_foreign_key(None, 'viagens', 'veiculos', ['veiculo_id'], ['id'])
    op.create_foreign_key(None, 'viagens', 'motoristas', ['motorista_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viagens', type_='foreignkey')
    op.drop_constraint(None, 'viagens', type_='foreignkey')
    op.drop_index(op.f('ix_viagens_id'), table_name='viagens')
    op.drop_column('viagens', 'veiculo_id')
    op.drop_column('viagens', 'motorista_id')
    op.drop_index(op.f('ix_motoristas_id'), table_name='motoristas')
    # ### end Alembic commands ###
