"""postos combustivel

Revision ID: bf8c701f1d59
Revises: 63694978501c
Create Date: 2026-05-23 22:13:55.086885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf8c701f1d59'
down_revision: Union[str, Sequence[str], None] = '63694978501c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postos_combustivel', sa.Column('gasoleo', sa.Float(), nullable=True))
    op.add_column('postos_combustivel', sa.Column('gasolina', sa.Float(), nullable=True))
    op.drop_column('postos_combustivel', 'preco_gasolina')
    op.drop_column('postos_combustivel', 'preco_gasoleo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postos_combustivel', sa.Column('preco_gasoleo', mysql.FLOAT(), nullable=True))
    op.add_column('postos_combustivel', sa.Column('preco_gasolina', mysql.FLOAT(), nullable=True))
    op.drop_column('postos_combustivel', 'gasolina')
    op.drop_column('postos_combustivel', 'gasoleo')
    # ### end Alembic commands ###
