"""criar servicos

Revision ID: d363c52aa2f4
Revises: 0810561c0210
Create Date: 2026-04-22 15:18:22.041527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd363c52aa2f4'
down_revision: Union[str, Sequence[str], None] = '0810561c0210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('manutencao', 'reparo', 'inspecao', name='tiposervico'), nullable=False),
    sa.Column('custo_estimado', sa.Float(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos')
    # ### end Alembic commands ###
