"""criar configuracoes_empresa

Revision ID: d87fbfd21b58
Revises: d363c52aa2f4
Create Date: 2026-04-22 15:42:03.112607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87fbfd21b58'
down_revision: Union[str, Sequence[str], None] = 'd363c52aa2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_empresa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome_empresa', sa.String(length=150), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes_empresa')
    # ### end Alembic commands ###
